

Select 
	WC.DIR_ID AS 'AJF_PROJ_CDE (C13)',
	OA.ACT_ID AS 'Activity ID (ACT_ID)', 
	OA.DESCRIPTION AS 'Activity Desc. (DESCRIPTION)',
	OC.TOTALFLOAT AS 'Total Float (TOTALFLOAT)', 
	OA.ORIG_DUR AS 'Original Duration (ORIG_DUR)',
	OA.BSDATE AS 'Baseline Start (BSDATE)',
	OA.BFDATE AS 'Baseline Finish (BFDATE)',
	OC.ESDATE AS 'Early Start (ESDATE)',
	OC.EFDATE AS 'Early Finish (EFDATE)',
	'' AS 'Actual Finish (AFDATE)',
	'' AS 'AJF_WBS_CMS (C10)',
	'' AS 'AJF_OBS_CMS (C11)',
	OC.COMPSTAT AS 'Computed Status (COMPSTAT)',
	OA.ACT_PROBABILITY AS 'Progress_Percent (Progress_Percent)',
	OA.ACT_TYPE AS 'Activity Type (ACT_TYPE)',
	'' AS 'AJF_CAM_CMS (C12)', 
	RES.RES_ID AS 'Resource ID',
	RES.DESCRIPTION AS 'Values'
	,OC.REM_DUR
	,OC.COMP_RS_C
	,OC.CRITICAL
	,OC.CRITINDEX
	,OC.ACTIVEINDEX
	,OC.SSINDEX
	,OC.FINFREEFLT
	,OC.FINTOTFLT
	,OC.FREEFLOAT
	,OC.MEAN_ES
	,OC.MEAN_EF
	,OC.BAC_QTY
	,OC.BAC_LAB
	,OC.BAC_MAT
	,OC.BAC_ODC
	,OC.BAC_SUB
	,OC.ETC_QTY
	,OC.ETC_LAB
	,OC.ETC_MAT
	,OC.ETC_ODC
	,OC.ETC_SUB
	,OC.ACWP_QTY
	,OC.ACWP_LAB
	,OC.ACWP_MAT
	,OC.ACWP_ODC
	,OC.ACWP_SUB
	,OC.BCWP_QTY
	,OC.BCWP_LAB
	,OC.BCWP_MAT
	,OC.BCWP_ODC
	,OC.BCWP_SUB
	,OC.BCWS_QTY
	,OC.BCWS_LAB
	,OC.BCWS_MAT
	,OC.BCWS_ODC
	,OC.BCWS_SUB
FROM OPP_ACT OA  
	LEFT JOIN WST_DIR WC ON OA.DIR_UID = WC.DIR_UID
	LEFT JOIN OPP_ACR OC ON OA.ACT_UID = OC.ACT_UID
	LEFT JOIN OPP_BSA BSA ON BSA.ACT_UID = OC.ACT_UID
	LEFT JOIN OPP_BCR OCB ON OCB.BSA_UID = BSA.BSA_UID
	LEFT JOIN OPP_RES RES ON RES.DIR_UID = WC.DIR_UID;

--Select * from ApplicationObjects O INNER JOIN ApplicationObjectTypes T ON T.ApplicationObjectTypeId = O.ApplicationObjectTypeId
